### ISSUE TITLE
Nova detect non-Docker files as Dockerfile

### ISSUE THREAD

**Issue by guillaumealgis** [photovirus/Dockerfile#4]
When having this extension enabled, Nova detects some files not related to Docker as Dockerfile.

For example, when opening a file named `0316_update_appointmentmotive-pregnant-discovery.py`, the default syntax is set to "Dockerfile" instead of the expected "Python".

I looked at the code, and I'm not sure what could be triggering such a behaviour, but maybe it is caused by an empty `preferred-file-extension` tag ?

Let me know if you need more info, it's relatively easy to reproduce for me.

**Comment by photovirus** [comment]
Hi!
File type detection uses file names and file content. It's quite possible first line resembles something from dockerfile syntax (e. g. “from ...” is used in python imports). 

It's strange though that python syntax detection doesn't recognize the file: “from...” has low priority.

**Comment by photovirus** [comment]
However, now that I've reviewed the source code again, it seems like I didn't implement “from...” syntax detection. I think exactly because the problem you're describing.

Here's the only thing that counts: filenames' matches.
```xml
	<detectors>
		<filename priority="1.0">Dockerfile</filename>
		<filename priority="1.0">dockerfile</filename>
		<filename priority="1.0">Containerfile</filename>
		<filename priority="1.0">containerfile</filename>
	</detectors>
```

**Comment by guillaumealgis** [comment]
Thanks for your response. I was not aware Nova did some kind of syntax detection. It seems to be the problem here : a Python file beginning with `from ... import ...` is detected as Dockerfile, while an empty file is detected as Python.

See the attached video, the file `fromimport.py` is incorrectly detected when the Dockerfile extension is enabled, and correctly when disabled.


https://user-images.githubusercontent.com/1041337/115603655-b6e88d80-a2e0-11eb-8c53-da0fe60137be.mov

**Comment by photovirus** [comment]
Interesting. It seems that having a dockerfile syntax highlighting rule is enough for the file to be recognized as a dockerfile, despite extension lacking a syntax detection rule.

Maybe it's a bug, or maybe a feature I don't know about—I wrote the extension *way back* during beta period. I'll ask people at Panic.

**Update.** Seems like a lot of documentation got released since I released the plugin; I'll have to check it up.

**Comment by minrk** [comment]
I believe this issue has already been fixed by [this commit](https://github.com/photovirus/Dockerfile.novaextension/commit/761292f93424c15c6ce8d6a73f3ba83c383f3e83#diff-07a64d82ad7cd05288d3f5e7a8046ffd070807f669de84a24266d9fea9058efc) removing the `from...` syntax detection, but there hasn't been an release of the plugin since the fix. Publishing a new release with what's here now might be all that's needed.

When I clone this repo and install from bd705765a872610196695e307f259cd890e70f6e, I don't see the issue anymore.

**Comment by photovirus** [comment]
You're right, thank you. Seems like I've forgot to make a release.

**Comment by photovirus** [comment]
Now that I've made a 1.0.1 release, the issue should get resolved.
